"use strict";
// صفحات OZAN التعريفية؛ لا ننشئ بيانات تواصل وهمية أو ندّعي وجود حسابات سحابية.
const OZ_INFO_PAGES={
 about:{title:"نبذة عنا",html:()=>`<div class="oz-about-hero"><h3>عرسي | نحو تجربة أذكى لإدارة المناسبات</h3><p>نطمح إلى بناء منظومة رقمية عربية تجعل التخطيط للمناسبات وإدارة الحجوزات أوضح وأكثر تنظيمًا؛ من اكتشاف الخدمات إلى متابعة المواعيد والمدفوعات والتواصل مع العميل.</p><p><strong>${escapeHtml(window.MyfntRepositories?.settings?.get?.('company.name')||"مايفنت")}</strong> هو جزء من هذه الرؤية: مساحة عملية لإدارة الحجوزات وتنظيم تفاصيلها من شاشة واحدة.</p></div><div class="oz-about-kpis"><div class="oz-about-kpi"><i class="fa-solid fa-calendar-check"></i><strong>تقويم ذكي</strong><span>المواعيد والتواريخ المتاحة</span></div><div class="oz-about-kpi"><i class="fa-solid fa-wallet"></i><strong>متابعة مالية</strong><span>العربون والدفعات والمتبقي</span></div><div class="oz-about-kpi"><i class="fa-solid fa-mobile-screen"></i><strong>واجهة متجاوبة</strong><span>مهيأة للاستخدام من الهاتف</span></div><div class="oz-about-kpi"><i class="fa-solid fa-cloud-arrow-up"></i><strong>جاهزية للتوسع</strong><span>طبقة تمهيدية للربط المستقبلي</span></div></div><section class="oz-about-panel"><h3>لماذا نبني عرسي؟</h3><p>هدفنا أن يجد أصحاب المناسبات ومقدمو الخدمات أدوات أبسط لتنسيق اليوم المهم: اكتشاف خيارات الخدمات، تنظيم المواعيد، تقليل تشتت المتابعة وتوثيق التعاملات. نتطلع لتطوير تجربة تناسب احتياجات السوق اليمنية وتكون قابلة للتوسع في العالم العربي.</p></section><section class="oz-about-panel"><h3>قدرات المنصة الحالية</h3><div class="oz-about-bars"><div class="oz-about-bar"><label><span>تنظيم الحجوزات والتقويم</span><span>متاح</span></label><meter min="0" max="1" value="1">متاح</meter></div><div class="oz-about-bar"><label><span>إدارة العربون والدفعات</span><span>متاح</span></label><meter min="0" max="1" value="1">متاح</meter></div><div class="oz-about-bar"><label><span>المزامنة السحابية الفعلية</span><span>قيد التطوير</span></label><meter min="0" max="1" value="0">قيد التطوير</meter></div></div><p class="oz-about-note">رسم توضيحي لحالة الميزات، وليس إحصاءات استخدام أو تقييمًا للأداء.</p></section><section class="oz-about-panel"><h3>التقنيات التي نعتمد عليها</h3><p>تجربة ويب قابلة للتثبيت (PWA)، تخزين محلي لاستمرارية الاستخدام، تقويم تفاعلي، إدارة لحالات الحجز وسجل الدفعات، تصدير ونسخ احتياطي، وتصميم يستجيب للشاشات المختلفة.</p></section><section class="oz-about-panel"><h3>الفريق والرؤية</h3><p>يقف خلف الرؤية عمل متعدد التخصصات يجمع تصميم الواجهات، وتطوير البرمجيات، وفهم إدارة خدمات المناسبات. نركز على تطوير منتجات عملية انطلاقًا من احتياجات المستخدم، مع التوسع المدروس وتحسين الخصوصية والموثوقية وتجربة الخدمة.</p><p>${escapeHtml(window.MyfntRepositories?.settings?.get?.('company.description')||"نتطلع إلى تجربة عربية مترابطة تجمع خدمات المناسبات وإدارتها.")}</p></section><p class="oz-about-note">البيانات في نسخة مايفنت الحالية محفوظة محليًا، وأي مزامنة سحابية معروضة هي محاكاة وليست نقلًا فعليًا إلى خادم. لا تمثل الرسوم أرقام إنجازات أو حجم فريق غير موثّق.</p>`},
 help:{title:"شرح الاستخدام",html:()=>`<h3>الحجوزات والتقويم</h3><p>انقر على تاريخ لتحديده، وانقر عليه ثانيةً لإلغاء التحديد. إذا كان به حجوزات، ستظهر بطاقاتها. اضغط مطولًا على يوم لفتح نموذج حجز جديد بالتاريخ المحدد.</p><h3>الأيام المتاحة</h3><p>اضغط رمز المشاركة بجانب عنوان الشهر، ثم انسخ التواريخ أو شاركها. يمكنك تغيير الشهر من الرمز المقابل.</p><h3>الحفظ والنسخ الاحتياطي</h3><p>البيانات محلية في هذا الإصدار؛ صدّر نسخة احتياطية من القائمة دوريًا، واحفظها في مكان آمن.</p><h3>تثبيت التطبيق</h3><p>افتح الموقع عبر HTTPS: في Chrome استخدم تثبيت التطبيق من القائمة إذا توفر؛ وفي Safari استخدم المشاركة ثم إضافة إلى الشاشة الرئيسية.</p>`},
 privacy:{title:"سياسة الخصوصية",html:()=>`<div class="oz-privacy" dir="rtl"><p><strong>آخر تحديث: 29 سبتمبر 2026</strong></p><h3>1. نطاق الخدمة</h3><p>مايفنت في هذا الإصدار تطبيق ويب لإدارة الحجوزات يعمل أساسًا بالتخزين المحلي في المتصفح، وليس خدمة مزامنة سحابية للحجوزات. يجب أن يراجع مالك الموقع هذه السياسة عند ربط أي خادم أو جهة معالجة بيانات جديدة.</p><h3>2. البيانات التي تدخلها</h3><p>قد تشمل اسم العميل، رقم الهاتف، تاريخ ووقت المناسبة، الباقة، الأسعار، العربون، المدفوعات والملاحظات وسجل التعديلات والتنبيهات وإعدادات النشاط التجاري.</p><h3>3. أين تخزن البيانات؟</h3><p>تُحفظ بيانات الحجوزات والإعدادات محليًا في تخزين المتصفح، وتستخدم النسخ الاحتياطية اليومية IndexedDB على الجهاز عند توفرها. محاكاة المزامنة لا تنقل الحجوزات إلى خادم بعيد ولا تحل محل النسخ الاحتياطي.</p><h3>4. الاتصالات الخارجية</h3><p>عند فتح الموقع قد تُرسل بيانات اتصال تقنية اعتيادية مثل عنوان IP ومعلومات المتصفح إلى خادم الاستضافة لتقديم الملفات، وقد يحتفظ مزود الاستضافة بسجلات وصول وفق إعداداته. تُحمّل الواجهة خط Almarai من Google Fonts، وقد تتلقى Google بيانات اتصال لازمة لتقديم الخط. إذا لم تحفظ دولةً مفضّلةً، يحاول نموذج الدخول اكتشاف الدولة عبر خدمة ipwho.is من عنوان IP دون طلب الموقع الجغرافي الدقيق؛ ويمكنك اختيار الدولة يدويًا بدلًا من ذلك. عند استخدام المشاركة أو روابط البريد وواتساب والمنصات الأخرى، تُنقل فقط المعلومات التي تختار إرسالها إلى تلك الخدمة وفق سياساتها.</p><h3>5. الأذونات والإشعارات</h3><p>إشعارات المتصفح لا تُفعَّل إلا بإذن صريح، ويمكن سحب الإذن من إعدادات المتصفح. تنبيهات الإصدار الحالي تعمل أساسًا أثناء فتح التطبيق؛ لا توجد خدمة Push سحابية مضمونة عند إغلاقه.</p><h3>6. الاحتفاظ والحذف والنسخ</h3><p>تظل البيانات المحلية على الجهاز إلى أن يحذفها المستخدم من داخل التطبيق أو يمسح بيانات الموقع في المتصفح، أو يتعرض التخزين لفقدان تقني. يمكن تصدير نسخة احتياطية واستعادتها. حذف الكاش لا يحذف عمدًا الحجوزات أو الدفعات، بينما مسح بيانات الموقع بالكامل قد يفعل ذلك.</p><h3>7. حماية المعلومات</h3><p>استخدم قفل الجهاز واحفظ النسخ الاحتياطية في مكان موثوق؛ فقد تحتوي على أسماء وأرقام هواتف وبيانات مالية. لا تدّعي هذه النسخة تشفير جميع النسخ المصدّرة، ولا ينبغي مشاركة ملف النسخة إلا مع المخوّلين.</p><h3>8. العملاء والحقوق</h3><p>مالك النشاط مسؤول عن إعلام العملاء بالأغراض التي يجمع بياناتهم من أجلها وعن التعامل مع طلبات الاطلاع أو التصحيح أو الحذف وفق الأنظمة السارية، مع مراعاة الالتزامات المحاسبية المشروعة. تُدار بيانات هذا الإصدار من الجهاز الذي حُفظت عليه.</p><h3>9. جهة التواصل والتحديثات</h3><p>للاستفسارات المتعلقة ببيانات نشاطك، استخدم معلومات التواصل التي يضعها مالك النشاط داخل التطبيق. يجب تحديث هذه السياسة قبل تفعيل المزامنة السحابية أو إرسال الرسائل تلقائيًا أو إضافة خدمات تحليل خارجية.</p></div>`},
 terms:{title:"شروط الاستخدام",html:()=>`<p>هذا الإصدار أداة محلية لإدارة الحجوزات. المستخدم مسؤول عن صحة الحجوزات والمبالغ، والحفاظ على نسخ احتياطية والتحقق من بيانات التصدير.</p><p>محاكاة المزامنة ليست نسخة احتياطية بعيدة ولا تضمن نقل الحجوزات بين الأجهزة. إشعارات التذكير تعتمد على أذونات الجهاز وفتح التطبيق ولا تُضمن عند إغلاقه بالكامل.</p><p>روابط التواصل التي يضيفها مالك النشاط مسؤوليته، ويجب الحصول على موافقة أصحاب البيانات قبل مشاركتها.</p>`}
};
function refreshOzanMenu(){
 const d=new Date(),hour=d.getHours();
 const greeting=d.getDay()===5?"جمعة مباركة":hour<12?"صباح الخير":"مساء الخير";
 const title=document.getElementById("ozGreeting");if(title)title.textContent=greeting+"، "+(window.OzanAuth?.data?.users?.find(u=>u.id===window.OzanScope?.read()?.userId)?.name?.trim().split(/\s+/)[0]||window.MyfntRepositories?.settings?.get?.('company.name')||"مايفنت");
 const dates=document.getElementById("ozMenuDates");if(dates){
  const greg=new Intl.DateTimeFormat("ar-YE-u-ca-gregory",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d);
  let hijri="";try{hijri=new Intl.DateTimeFormat("ar-SA-u-ca-islamic-umalqura",{day:"numeric",month:"long",year:"numeric"}).format(d);}catch{hijri="التاريخ الهجري غير متاح";}
  dates.textContent=greg+" | "+hijri;
 }
 const c=window.MyfntRepositories?.settings?.get?.('company')||{},host=document.getElementById("ozSocialLinks");if(!host)return;
 host.replaceChildren();
 const digits=s=>String(s||"").replace(/[^0-9]/g,"");
 const entries=[
  ["instagram",c.instagram,"إنستقرام","fa-camera"],["facebook",c.facebook,"فيسبوك","fa-users"],
  ["whatsapp",digits(c.whatsapp||c.phone)?"https://wa.me/"+digits(c.whatsapp||c.phone):"","واتساب","fa-comment-dots"],
  ["email",c.email?"mailto:"+c.email:"","البريد الإلكتروني","fa-envelope"],
  ["phone",digits(c.phone)?"tel:+"+digits(c.phone):"","اتصال","fa-phone"],
  ["map",c.map,"الخريطة","fa-map-location-dot"]];
 entries.forEach(([key,url,label,icon])=>{
  if(!url)return;
  if(["instagram","facebook","map"].includes(key)){try{const parsed=new URL(url);if(!["https:","http:"].includes(parsed.protocol))return;}catch{return;}}
  const link=document.createElement("a");link.className="oz-social-link";link.href=url;link.target=key==="email"||key==="phone"?"_self":"_blank";link.rel="noopener noreferrer";link.setAttribute("aria-label",label);link.title=label;
  const brands={
 instagram:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/>',
 facebook:'<path d="M15 21v-8h3l.5-4H15V7c0-1.1.4-1.5 1.5-1.5H19V2.2C18.4 2.1 17.4 2 16.2 2 13 2 11.6 4 11.6 6.5V9H9v4h2.6v8z" fill="currentColor" stroke="none"/>',
 whatsapp:'<path d="M20.5 11.6a8.5 8.5 0 0 1-12.4 7.5L3 20.5l1.4-4.9a8.5 8.5 0 1 1 16.1-4z"/><path d="M8 8.5c.5 3 3.5 5.7 6.8 6.8.7.1 1.7-.5 1.9-1.2l-2.2-1.1-1 1c-1.4-.6-2.5-1.6-3.2-3.1l.8-1-1.3-2z"/>',
 };
 if(brands[key]){const iconSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');iconSvg.setAttribute('viewBox','0 0 24 24');iconSvg.setAttribute('width','22');iconSvg.setAttribute('height','22');iconSvg.setAttribute('aria-hidden','true');iconSvg.setAttribute('fill','none');iconSvg.setAttribute('stroke','currentColor');iconSvg.setAttribute('stroke-width','1.8');iconSvg.setAttribute('stroke-linecap','round');iconSvg.innerHTML=brands[key];link.append(iconSvg);}
 else{const i=document.createElement("i");i.className="fa-solid "+icon;i.setAttribute("aria-hidden","true");link.append(i);}
 host.append(link);
 });
}
function initOzanInfoPages(){
 document.getElementById("menuBtn")?.addEventListener("click",refreshOzanMenu);
 document.getElementById("menuWindow")?.addEventListener("click",e=>{
  const button=e.target.closest("[data-oz-info]");if(!button)return;
  const page=OZ_INFO_PAGES[button.dataset.ozInfo];if(!page)return;
  document.getElementById("ozInfoTitle").textContent=page.title;
  document.getElementById("ozInfoContent").innerHTML=page.html();switchWindow("ozInfoWindow");
 });

 refreshOzanMenu();
}
