/* Myfnt 2.14.0 Step 22A.6 — Canonical domain/row/API mappers.
 * One semantic mapping contract for packages, customers, bookings and payments.
 * Transitional consumers may keep fallbacks, but new conversions should use this module.
 */
'use strict';
(()=>{
 const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
 const str=(v,d='')=>v==null?d:String(v);
 const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
 const minor=v=>Math.round((Number(v)||0)*100);
 const major=v=>(Number(v)||0)/100;
 const ms=(v,f=0)=>{if(typeof v==='number'&&Number.isFinite(v))return v;const n=Date.parse(v||'');return Number.isFinite(n)?n:Number(f||0);};
 const iso=v=>{if(!v)return null;if(typeof v==='number'){const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString();}const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toISOString();};
 const legacyId=row=>str(row?.legacy_id||row?.id);
 const phone=v=>window.MyfntCustomers?.normalizePhone?.(v)||str(v).replace(/[^+\d]/g,'')||null;
 const phoneKey=v=>window.MyfntCustomers?.phoneKey?.(v)||str(v).replace(/\D/g,'');
 const nameKey=v=>window.MyfntCustomers?.nameKey?.(v)||str(v).trim().toLowerCase();
 const search=parts=>parts.filter(v=>v!=null&&v!=='').join(' ').toLowerCase().replace(/\s+/g,' ').trim();
 const currency=v=>str(v||'YER').toUpperCase();
 const time=v=>{if(!v)return '';const m=str(v).match(/(?:T|^)(\d{2}:\d{2})/);return m?m[1]:str(v).slice(0,5);};
 const rawOf=row=>row?.legacy_raw&&typeof row.legacy_raw==='object'?clone(row.legacy_raw):{};
 const statusToRow=s=>s==='archived'?'archived':s==='cancelled'?'cancelled':s==='completed'?'completed':'active';
 const statusFromRow=row=>row.status==='archived'?'archived':row.status==='cancelled'?'cancelled':row.status==='completed'?'completed':row.confirmation==='temporary'?'pending':'confirmed';
 const packageMapper={
  async toRow(p,ctx={}){const id=await ctx.uuidFor('booking_packages',p.id);return {table:'booking_packages',id,company_id:ctx.company_id,legacy_id:p.id,name:p.name||'باقة',icon:p.icon||null,regular_price_minor:minor(p.price),season_price_minor:minor(p.seasonPrice),default_deposit_minor:minor(p.deposit),currency:currency(ctx.currency),status:p.status==='hidden'?'hidden':'active',allow_double_booking:!!p.allowDoubleBooking,allow_discount:p.allowDiscount!==false,package_version:Number(p.version)||1,built_in_local:!!p.builtIn};},
  fromRow(row){const raw=rawOf(row);return {...raw,id:legacyId(row),name:row.name||raw.name||'باقة',icon:row.icon||raw.icon||'fa-star',price:major(row.regular_price_minor),seasonPrice:major(row.season_price_minor),deposit:major(row.default_deposit_minor),status:row.status==='hidden'?'hidden':'active',allowDoubleBooking:!!row.allow_double_booking,allowDiscount:row.allow_discount!==false,builtIn:row.built_in_local??raw.builtIn??/^p[1-5]$/.test(legacyId(row)),version:Number(row.package_version||raw.version||1)};}
 };
 const customerMapper={
  async toRow(c,ctx={}){const id=await ctx.uuidFor('customers',c.id);const notes=ctx.notes?.[c.id]||c.notes||'';return {table:'customers',id,company_id:ctx.company_id,legacy_id:c.id,customer_no:c.customerNo||'',name:str(c.name).trim(),phone_e164:phone(c.phone),phone_key:phoneKey(c.phone),name_key:nameKey(c.name),search_text:search([c.customerNo,c.name,c.phone,c.address,notes]),address:c.address||'',notes};},
  fromRow(row){return {id:legacyId(row),customerNo:str(row.customer_no),name:str(row.name).trim(),phone:str(row.phone_e164),address:str(row.address),notes:str(row.notes),createdAt:ms(row.created_at||row.local_created_at),updatedAt:ms(row.updated_at||row.local_updated_at)};}
 };
 const bookingMapper={
  async toRows(b,ctx={}){const bk=await ctx.uuidFor('bookings',b.id),customerLegacy=b.customerId||('legacy-booking:'+b.id),customer_id=await ctx.uuidFor('customers',customerLegacy),package_id=b.packageId?await ctx.uuidFor('booking_packages',b.packageId):null,pkg=ctx.packagesById?.get?.(b.packageId),ps=b.pricingSnapshot||{},adjustments=Array.isArray(b.adjustments)?b.adjustments:[],discount=adjustments.filter(a=>a.kind==='discount').reduce((n,a)=>n+Number(a.value||0),0),surcharge=adjustments.filter(a=>a.kind==='add').reduce((n,a)=>n+Number(a.value||0),0),agreed=minor(b.amount),listRaw=ps.listPrice!=null?Number(ps.listPrice):Number(b.amount||0)-surcharge+discount,listPrice=minor(Math.max(0,listRaw));
   const booking={table:'bookings',id:bk,company_id:ctx.company_id,legacy_id:b.id,booking_no:str(b.bookingNo),customer_id,event_date:str(b.date),starts_at:b.hasTime?b.timeFrom||null:null,ends_at:b.hasTime?b.timeTo||null:null,confirmation:b.status==='pending'?'temporary':'confirmed',temporary_expires_at:iso(b.temporaryExpiresAt),status:statusToRow(b.status),amount_minor:agreed,paid_minor:minor(Math.max(0,Number(b.paid||0))),currency:currency(b.currency||ctx.currency),customer_name_snapshot:str(b.name),customer_phone_snapshot:phone(b.phone),package_name_snapshot:str(ps.packageName||b.type||pkg?.name||'مناسبة'),search_text:search([b.bookingNo,b.id,b.name,b.phone,b.type,b.date,b.notes]),server_version:Number(b.serverVersion)||0,local_updated_at:iso(b.updatedAt),local_created_at:iso(b.createdAt),created_by_id:b.createdById||null,created_by_name:b.createdBy||null,updated_by_id:b.updatedById||b.createdById||null,updated_by_name:b.updatedBy||b.createdBy||null};
   const detail={table:'booking_details',id:await ctx.uuidFor('booking_details',b.id),company_id:ctx.company_id,booking_id:bk,legacy_id:b.id,customer_name_snapshot:b.name||'',customer_phone_snapshot:phone(b.phone),address_snapshot:b.address||'',description:b.notes||'',package_id,package_version:pkg?.version||null,package_name_snapshot:ps.packageName||b.type||pkg?.name||'مناسبة',package_price_minor_snapshot:listPrice,deposit_minor_snapshot:minor(ps.depositRequired??b.depositRequired??0),discount_minor:minor(discount),surcharge_minor:minor(surcharge),adjustment_reason:adjustments.map(a=>a.reason).filter(Boolean).join('؛ '),agreed_total_minor:agreed,currency:currency(b.currency||ctx.currency),legacy_snapshot_unverified:str(ps.source).includes('unverified')||!b.pricingSnapshot};
   return {booking,detail};
  },
  fromRows(row,detail,ctx={}){if(!row)return null;const raw=rawOf(row),c=ctx.customersByUuid?.get?.(str(row.customer_id)),p=detail?.package_id?ctx.packagesByUuid?.get?.(str(detail.package_id)):null,status=statusFromRow(row),created=ms(row.local_created_at||row.created_at),updated=ms(row.local_updated_at||row.updated_at),next={...raw,id:legacyId(row),bookingNo:str(row.booking_no||raw.bookingNo),customerId:c?.id||raw.customerId||'',name:str(detail?.customer_name_snapshot||c?.name||raw.name).trim(),phone:str(detail?.customer_phone_snapshot||c?.phone||raw.phone),address:str(detail?.address_snapshot||c?.address||raw.address),date:str(row.event_date||raw.date),type:str(detail?.package_name_snapshot||p?.name||raw.type||'مناسبة خاصة'),packageId:p?.id||raw.packageId||'',status,hasTime:Boolean(row.starts_at||row.ends_at),timeFrom:time(row.starts_at)||raw.timeFrom||'09:00',timeTo:time(row.ends_at)||raw.timeTo||'21:00',amount:detail?major(detail.agreed_total_minor):Number(raw.amount||major(row.amount_minor)||0),paid:Number.isFinite(Number(row.paid_minor))?major(row.paid_minor):Number(raw.paid||0),notes:str(detail?.description??raw.notes),currency:currency(detail?.currency||row.currency||raw.currency),temporaryExpiresAt:row.temporary_expires_at?ms(row.temporary_expires_at):Number(raw.temporaryExpiresAt||0),depositPending:status==='pending'&&Number(detail?.deposit_minor_snapshot||0)>0,depositRequired:detail?major(detail.deposit_minor_snapshot):Number(raw.depositRequired||0),serverVersion:Number(row.server_version??row.version??raw.serverVersion??0),syncStatus:ctx.syncStatus||'synced',createdById:row.created_by_id||raw.createdById||'',createdBy:row.created_by_name||raw.createdBy||'مستخدم',updatedById:row.updated_by_id||raw.updatedById||row.created_by_id||'',updatedBy:row.updated_by_name||raw.updatedBy||row.created_by_name||'مستخدم',createdAt:created,updatedAt:updated};
   if(detail){next.pricingSnapshot={...(raw.pricingSnapshot||{}),packageId:next.packageId,packageName:next.type,listPrice:major(detail.package_price_minor_snapshot),depositRequired:major(detail.deposit_minor_snapshot),currency:next.currency,source:detail.legacy_snapshot_unverified?'server-legacy-unverified':'server',effectiveAt:updated};const a=[];if(Number(detail.discount_minor)>0)a.push({kind:'discount',value:major(detail.discount_minor),reason:detail.adjustment_reason||'',at:updated});if(Number(detail.surcharge_minor)>0)a.push({kind:'add',value:major(detail.surcharge_minor),reason:detail.adjustment_reason||'',at:updated});if(a.length)next.adjustments=a;}
   return typeof normalizeBooking==='function'?(normalizeBooking(next)||null):next;
  }
 };
 const paymentMapper={
  async toRow(r,ctx={}){const bk=ctx.booking||ctx.bookingsByLegacy?.get?.(str(r.bookingId)),hasBooking=Boolean(bk&&r.bookingId),customerLegacy=str(r.customerId||bk?.customerId||'');return {table:'payments',id:await ctx.uuidFor('payments',r.id),company_id:ctx.company_id,legacy_id:r.id,booking_id:hasBooking?await ctx.uuidFor('bookings',r.bookingId):null,booking_legacy_id:hasBooking?str(r.bookingId):'',receipt_no:str(r.receiptNo||r.id),movement_no:str(r.movementNo),customer_id:customerLegacy?await ctx.uuidFor('customers',customerLegacy):null,customer_legacy_id:customerLegacy,direction:r.direction==='out'?'out':'in',amount_minor:minor(r.amount),currency:currency(bk?.currency||r.currency||ctx.currency),payment_method:r.method||'cash',external_reference:r.reference||null,memo:r.note||'',tag:r.tag||null,posted_at:r.date?`${r.date}T12:00:00.000Z`:iso(r.createdAt),status:r.status==='voided'?'reversed':'posted',reversal_reason:r.voidReason||null,booking_no_snapshot:str(bk?.bookingNo),customer_name_snapshot:str(bk?.name||r.customerName),customer_phone_snapshot:phone(bk?.phone||r.customerPhone),search_text:search([r.id,r.receiptNo,r.movementNo,r.reference,r.tag,r.note,bk?.bookingNo,bk?.name,bk?.phone,r.customerName,r.customerPhone]),edited_by_name_snapshot:r.editedByName||r.createdBy||null,created_by_id:r.createdById||null,created_by_name:r.createdBy||null,edited_by_id:r.editedById||r.createdById||null};},
  fromRow(row,ctx={}){if(!row)return null;const raw=rawOf(row),b=ctx.bookingByUuid?.get?.(str(row.booking_id)),c=ctx.customerByUuid?.get?.(str(row.customer_id));return {...raw,id:legacyId(row),receiptNo:str(row.receipt_no||raw.receiptNo||legacyId(row)),movementNo:str(row.movement_no||raw.movementNo),bookingId:b?.id||raw.bookingId||str(row.booking_legacy_id),customerId:c?.id||b?.customerId||raw.customerId||str(row.customer_legacy_id),direction:row.direction==='out'?'out':'in',amount:major(row.amount_minor),currency:currency(row.currency||b?.currency||raw.currency),method:row.payment_method||raw.method||'cash',reference:row.external_reference||raw.reference||'',note:row.memo??raw.note??'',tag:row.tag??raw.tag??'',date:str(row.posted_at||raw.date).slice(0,10),status:['reversed','voided'].includes(row.status)?'voided':'active',voidReason:row.reversal_reason||raw.voidReason||'',createdById:row.created_by_id||raw.createdById||'',createdBy:row.created_by_name||row.edited_by_name_snapshot||raw.createdBy||'مستخدم',editedById:row.edited_by_id||raw.editedById||'',editedByName:row.edited_by_name_snapshot||raw.editedByName||'',createdAt:ms(row.posted_at||raw.createdAt),updatedAt:ms(row.updated_at||row.posted_at||raw.updatedAt)};}
 };
 const API_FIELDS={};
 function toApi(table,row,allowed){const out={};for(const k of allowed||API_FIELDS[table]||[])if(Object.hasOwn(row,k))out[k]=clone(row[k]);return out;}
 function contract(){return {version:1,authority:'indexeddb',identity:'client_uuid_is_canonical',entities:['booking_packages','customers','bookings','booking_details','payments'],money:'minor-in-row-major-in-ui',dates:'iso-in-row-ms-in-ui'};}
 function audit(){const checks={package:Boolean(packageMapper.toRow&&packageMapper.fromRow),customer:Boolean(customerMapper.toRow&&customerMapper.fromRow),booking:Boolean(bookingMapper.toRows&&bookingMapper.fromRows),payment:Boolean(paymentMapper.toRow&&paymentMapper.fromRow),api:Boolean(toApi)};return {healthy:Object.values(checks).every(Boolean),checks,contract:contract(),version:'1.0.0'};}
 window.MyfntMappers=Object.freeze({version:'1.0.0',package:packageMapper,customer:customerMapper,booking:bookingMapper,payment:paymentMapper,legacyId,toApi,contract,audit});
})();
