/* OZAN 2.2.3: functional offline team preview, scoped by company; NOT an authorization boundary. */
'use strict';
(()=>{
 const el=id=>document.getElementById(id),session=()=>window.OzanScope?.read(),auth=()=>window.OzanAuth;
 const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const CAPS=[['bookings.read','عرض الحجوزات','fa-calendar-days'],['bookings.write','إضافة وتعديل الحجوزات','fa-calendar-plus'],['payments.write','قبض الدفعات والسندات','fa-file-invoice-dollar'],['packages.write','تعديل الباقات والأسعار','fa-tags'],['settings.write','إعدادات النظام والتقويم','fa-gears'],['team.read','عرض الجلسات','fa-laptop-mobile'],['team.write','إدارة الجلسات','fa-mobile-screen-button'],['exports.read','تصدير البيانات','fa-file-export'],['support.write','بريد الدعم','fa-envelope-open-text'],['messages.approve','الموافقة على رسائل SMS القصوى','fa-shield-halved']];
 const ROLES={owner:CAPS.map(x=>x[0])};
 const workspace=()=>{const s=session();return s?'ozan.tools.v221.'+encodeURIComponent(s.companyId):'';};
 const read=()=>{try{return JSON.parse(localStorage.getItem(workspace())||'{}')}catch{return {}}};
 const save=x=>{localStorage.setItem(workspace(),JSON.stringify(x));};
 const current=()=>{const s=session(),data=auth()?.data;return s&&data?{s,user:data.users.find(u=>u.id===s.userId),company:data.companies.find(c=>c.id===s.companyId)}:null;};
 // Step21L: one principal account, multiple device sessions. Legacy role/permission helpers
 // remain as compatibility shims for older modules, but no longer divide access by role.
 const owner=()=>Boolean(current()?.user);
 const permissions=()=>current()?.user?CAPS.map(a=>a[0]):[];
 const can=cap=>Boolean(current()?.user)&&CAPS.some(a=>a[0]===cap);
 function denied(cap){if(can(cap))return false;showToast('سجّل الدخول بالحساب الرئيسي لتنفيذ هذا الإجراء','warning');return true;}
 window.OzanPermissions={caps:CAPS,roles:ROLES,can,owner,permissions,denied};
 const logged=()=>{if(!session()){auth()?.open?.();return false;}return true;};
 const DEVICE_ID_KEY='myfnt.device.id.v1',DEVICE_NAME_KEY='myfnt.device.name.v1',SESSION_STORE='ozan.auth.session.v1';
 const randomId=()=>crypto?.randomUUID?.()||('sess-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));
 const deviceId=()=>{let id=localStorage.getItem(DEVICE_ID_KEY);if(!id){id=randomId();try{localStorage.setItem(DEVICE_ID_KEY,id);}catch{}}return id;};
 const inferredDeviceName=()=>{const platform=navigator.userAgentData?.platform||navigator.platform||'';const mobile=navigator.userAgentData?.mobile||/Android|iPhone|iPad|Mobile/i.test(navigator.userAgent||'');if(/android/i.test(platform+navigator.userAgent))return 'هاتف Android';if(/iphone|ipad/i.test(platform+navigator.userAgent))return 'iPhone / iPad';if(/win/i.test(platform))return 'كمبيوتر Windows';if(/mac/i.test(platform))return 'جهاز Mac';return mobile?'هاتف هذا الجهاز':'هذا الكمبيوتر';};
 const knownDeviceName=()=>String(localStorage.getItem(DEVICE_NAME_KEY)||'').trim()||inferredDeviceName();
 const sessionsKey=()=>{const s=session();return s?`myfnt.sessions.v1.${encodeURIComponent(s.userId)}.${encodeURIComponent(s.companyId)}`:'';};
 const readSessions=()=>{try{const rows=JSON.parse(localStorage.getItem(sessionsKey())||'[]');return Array.isArray(rows)?rows:[]}catch{return []}};
 const saveSessions=rows=>{const key=sessionsKey();if(!key)return;try{localStorage.setItem(key,JSON.stringify(rows.slice(0,40)));}catch{}};
 function ensureCurrentSession(){const s=session();if(!s)return null;let changed=false;if(!s.sessionId){s.sessionId=randomId();changed=true;}if(!s.deviceId){s.deviceId=deviceId();changed=true;}if(!s.deviceName){s.deviceName=knownDeviceName();changed=true;}if(!s.createdAt){s.createdAt=Date.now();changed=true;}s.lastSeenAt=Date.now();if(changed)try{localStorage.setItem(SESSION_STORE,JSON.stringify(s));}catch{}
  const rows=readSessions(),i=rows.findIndex(x=>x.id===s.sessionId),row={id:s.sessionId,deviceId:s.deviceId,name:s.deviceName||knownDeviceName(),createdAt:Number(s.createdAt||Date.now()),lastSeenAt:Date.now(),browser:navigator.userAgentData?.brands?.map(x=>x.brand).join(', ')||(/Chrome/i.test(navigator.userAgent)?'Chrome':/Safari/i.test(navigator.userAgent)?'Safari':'المتصفح'),platform:navigator.userAgentData?.platform||navigator.platform||'',current:true};
  rows.forEach(x=>x.current=false);if(i>=0)rows[i]={...rows[i],...row};else rows.unshift(row);rows.sort((a,b)=>Number(b.lastSeenAt||0)-Number(a.lastSeenAt||0));saveSessions(rows);return row;
 }
 const fmtSeen=t=>{const n=Number(t||0);if(!n)return 'غير معروف';const d=Math.max(0,Date.now()-n);if(d<60000)return 'الآن';if(d<3600000)return `منذ ${Math.max(1,Math.floor(d/60000))} د`;if(d<86400000)return `منذ ${Math.max(1,Math.floor(d/3600000))} س`;return new Date(n).toLocaleDateString('ar-YE',{year:'numeric',month:'short',day:'numeric'});};
 function renderTeam(){const cur=ensureCurrentSession(),rows=readSessions();const input=el('ozDeviceSessionName');if(input&&cur)input.value=cur.name||knownDeviceName();const host=el('ozTeamDrafts');if(!host)return;host.innerHTML=rows.length?rows.map(x=>`<article class="oz-member-card ${x.current?'is-current':''}"><span class="oz-member-avatar"><i class="fa-solid ${x.current?'fa-mobile-screen-button':'fa-display'}"></i></span><div><strong>${html(x.name||'جهاز بدون اسم')} ${x.current?'<em class="mf-session-current">هذه الجلسة</em>':''}</strong><small>${html([x.platform,x.browser].filter(Boolean).join(' · ')||'جهاز معروف')}</small><small>آخر نشاط: ${html(fmtSeen(x.lastSeenAt))}</small></div></article>`).join(''):'<p class="oz-prod-muted">لا توجد جلسات مسجلة محليًا بعد.</p>';}
 function renameCurrentSession(name){const s=session();if(!s)return false;name=String(name||'').trim().replace(/\s+/g,' ');if(name.length<2||name.length>50)return false;s.sessionId=s.sessionId||randomId();s.deviceId=s.deviceId||deviceId();s.deviceName=name;s.lastSeenAt=Date.now();try{localStorage.setItem(DEVICE_NAME_KEY,name);localStorage.setItem(SESSION_STORE,JSON.stringify(s));}catch{return false;}const rows=readSessions(),i=rows.findIndex(x=>x.id===s.sessionId),row={id:s.sessionId,deviceId:s.deviceId,name,createdAt:Number(s.createdAt||Date.now()),lastSeenAt:Date.now(),browser:navigator.userAgentData?.brands?.map(x=>x.brand).join(', ')||'',platform:navigator.userAgentData?.platform||navigator.platform||'',current:true};rows.forEach(x=>x.current=false);if(i>=0)rows[i]={...rows[i],...row};else rows.unshift(row);saveSessions(rows);return true;}
 function activityContext(){const x=current(),t=window.OzanAuthData?.businessTypes?.find(v=>v.id===x?.company?.type);return t||{label:'نشاطك',description:'إدارة حجوزات ودفعات نشاطك باحتراف.'};}
 function ensureSubscriptionDates(){const x=current();if(!x?.company)return null;let changed=false;if(!x.company.planStartedAt){x.company.planStartedAt=x.company.createdAt?new Date(x.company.createdAt).toISOString():new Date().toISOString();changed=true;}if(!x.company.planExpiresAt){x.company.planExpiresAt=new Date(new Date(x.company.planStartedAt).getTime()+365*86400000).toISOString();changed=true;}if(changed)try{localStorage.setItem('ozan.auth.demo.v1',JSON.stringify(auth().data));}catch{}return x.company;}
 const formatSubDate=v=>v?new Date(v).toLocaleDateString('ar-YE',{year:'numeric',month:'long',day:'numeric'}):'—';
 function planDescription(p,activity){return `${p.tagline||p.features_note||`${p.name_ar} مناسبة لـ${activity.label}.`}`;}
 const planLimit=v=>v===-1||v==null?'غير محدود':Number(v).toLocaleString('en-US');
 const planYes=v=>v===true?'<i class="fa-solid fa-circle-check"></i> متاح':'<i class="fa-solid fa-circle-xmark"></i> غير متاح';
 const bytesLabel=v=>v==null?'غير محدود':Number(v)<=0?'غير متاح':Number(v)>=1073741824?`${(Number(v)/1073741824).toLocaleString('en-US',{maximumFractionDigits:1})} GB`:`${Math.round(Number(v)/1048576).toLocaleString('en-US')} MB`;
 function planDetails(p){const rows=[
  ['fa-calendar-check','عدد الحجوزات',planLimit(p.bookings_limit)],
  ['fa-user-group','عدد مستخدمي الشركة',planLimit(p.users_limit)],
  ['fa-message','عدد الرسائل الشهرية',planLimit(p.sms_monthly_limit)],
  ['fa-comments','عدد الرسائل السنوية',planLimit(p.sms_yearly_limit)],
  ['fa-mobile-screen-button','عدد أرقام الرسائل',planLimit(p.message_numbers_limit)],
  ['fa-tags','عدد الباقات',planLimit(p.packages_limit)],
  ['fa-calendar-days','مزامنة Google Calendar',planYes(p.google_calendar_sync)],
  ['fa-hard-drive','مزامنة Google Drive',planYes(p.google_drive_sync)],
  ['fa-cloud','المزامنة مع Cloud',planYes(p.cloud_sync)],
  ['fa-link','عدد حسابات التكامل',planLimit(p.integration_accounts_limit)],
  ['fa-database','نسخة احتياطية مخصصة',planYes(p.manual_backup)],
  ['fa-clock-rotate-left','نسخة احتياطية يومية',planYes(p.daily_backup)],
  ['fa-database','مساحة النسخ الاحتياطية',bytesLabel(p.backup_storage_bytes)],
  ['fa-layer-group','عدد النسخ المحفوظة',planLimit(p.backup_retention_limit)],
  ['fa-trash','الاستعادة من المهملات',planYes(p.trash_restore)],
  ['fa-calendar-day','مدة الاحتفاظ بالمهملات',p.trash_retention_days==null?'غير محدود':`${Number(p.trash_retention_days).toLocaleString('en-US')} يوم`],
  ['fa-file-excel','تصدير الحجوزات إلى Excel',planYes(p.bookings_excel_export)],
  ['fa-file-export','تصديرات شهرية',planLimit(p.exports_monthly_limit)],
  ['fa-receipt','تنزيل سند الحجز',planYes(p.booking_receipt_download)],
  ['fa-file-invoice-dollar','تنزيل سند القبض',planYes(p.payment_receipt_download)],
  ['fa-paper-plane','إرسال تلقائي بدون موافقة',planYes(p.auto_message_send)],
  ['fa-comment-sms','بوابة SMS مخصصة',planYes(p.custom_sms_gateway)],
  ['fa-comment-sms','مركز رسائل متقدم',planYes(p.advanced_message_center)],
  ['fa-building','إعدادات شركة متقدمة',planYes(p.advanced_company_settings)],
  ['fa-calendar-week','تخصيص التقويم المتقدم',planYes(p.calendar_customization)],
  ['fa-sliders','تخصيص فورم الحجز',planYes(p.booking_form_customization)]
 ];return rows.map(([icon,label,value])=>`<span class="mf-plan-detail"><i class="fa-solid ${icon}"></i><small>${html(label)}</small><b>${value}</b></span>`).join('');}
 function renderPlan(){const d=read(),x=current();if(!x)return;const company=ensureSubscriptionDates(),activity=activityContext(),bookings=(window.MyfntRepositories?.bookings?.all?.()||[]),payments=(window.MyfntRepositories?.payments?.all?.()||[]),members=readSessions().length;
  const registry=window.MyfntPlans,currentCode=String(company?.plan||registry?.defaultCode?.()||'ULTRA').toUpperCase(),plans=registry?.all?.()||[];
  if(!plans.length){el('ozPlanContent').innerHTML='<div class="oz-prod-panel"><h3><i class="fa-solid fa-spinner fa-spin"></i> جارٍ تحميل الخطط...</h3></div>';registry?.ready?.().then(renderPlan).catch(()=>{});return;}
  const limit=v=>v===-1||v==null?'∞':Number(v).toLocaleString('en-US'),price=(v,c='YER')=>v==null?'من الإدارة':`${Number(v).toLocaleString('en-US')} ${c==='YER'?'ر.ي':c}`;
  const planIcon={BASIC:'fa-seedling',PLUS:'fa-bolt',SUPER:'fa-gem',ULTRA:'fa-crown'};
  const request=(d.upgradeRequests||[]).find(r=>['pending','cancel_requested'].includes(r.status));
  const active=plans.find(p=>p.code===currentCode)||plans.find(p=>p.code===registry?.defaultCode?.())||plans[0];
  const cards=plans.map(p=>{const current=p.code===currentCode;return `<article class="mf-plan-card ${current?'is-current':''} ${p.code==='ULTRA'?'is-ultra':''} ${request?'is-locked':''}" data-plan-card="${html(p.code)}"><div class="mf-plan-card__top"><span class="mf-plan-icon"><i class="fa-solid ${planIcon[p.code]||'fa-layer-group'}"></i></span><div><div class="mf-plan-card__head"><span class="mf-plan-code">${html(p.code)}</span>${current?'<b><i class="fa-solid fa-circle-check"></i> الحالية</b>':''}${p.code==='ULTRA'?'<em class="mf-plan-best">كل الميزات</em>':''}</div><h3>${html(p.name_ar)} <small>${html(p.name_en)}</small></h3></div></div><p class="mf-plan-note">${html(planDescription(p,activity))}</p><div class="mf-plan-prices"><span><small>شهري</small><b>${price(p.monthly_price,p.currency)}</b></span><span><small>سنوي</small><b>${price(p.annual_price,p.currency)}</b></span></div><div class="mf-plan-feature-grid"><span><i class="fa-solid fa-calendar-check"></i><small>الحجوزات</small><b>${limit(p.bookings_limit)}</b></span><span><i class="fa-solid fa-user-group"></i><small>المستخدمون</small><b>${limit(p.users_limit)}</b></span><span><i class="fa-solid fa-message"></i><small>SMS شهري</small><b>${limit(p.sms_monthly_limit)}</b></span><span><i class="fa-solid fa-mobile-screen"></i><small>أرقام الرسائل</small><b>${limit(p.message_numbers_limit)}</b></span><span><i class="fa-solid fa-tags"></i><small>الباقات</small><b>${limit(p.packages_limit)}</b></span><span><i class="fa-solid fa-database"></i><small>النسخ</small><b>${limit(p.backup_retention_limit)}</b></span></div><button type="button" class="mf-plan-more" data-plan-more="${html(p.code)}" aria-expanded="false"><i class="fa-solid fa-chevron-down"></i><span>عرض المزيد</span></button><div class="mf-plan-details" data-plan-details="${html(p.code)}" hidden>${planDetails(p)}</div>${!current&&!request?`<button type="button" class="mf-plan-upgrade" data-plan-upgrade="${html(p.code)}"><i class="fa-solid fa-arrow-up-right-dots"></i> اختيار الخطة</button>`:''}${request?'<div class="mf-plan-lock"><i class="fa-solid fa-lock"></i> الاختيار مغلق أثناء مراجعة طلب الترقية</div>':''}</article>`}).join('');
  el('ozPlanContent').innerHTML=`<div class="oz-plan-hero"><div><span>${html(activity.label)} · اشتراك شركتك</span><h3><i class="fa-solid ${planIcon[active?.code]||'fa-crown'}"></i> ${html(active?.code||'ULTRA')} — ${html(active?.name_ar||'الترا')}</h3><p>${html(planDescription(active,activity))}</p></div><div class="oz-plan-mini"><span><b>${bookings.length}</b> حجز</span><span><b>${payments.length}</b> سند</span><span><b>${members}</b> جلسة</span></div></div><div class="mf-sub-dates"><span><i class="fa-solid fa-calendar-plus"></i><small>بداية الاشتراك</small><b>${html(formatSubDate(company?.planStartedAt))}</b></span><span><i class="fa-solid fa-calendar-xmark"></i><small>انتهاء الاشتراك</small><b>${html(formatSubDate(company?.planExpiresAt))}</b></span></div>${request?`<div class="mf-upgrade-pending ${request.status==='cancel_requested'?'is-cancel-requested':''}"><i class="fa-solid ${request.status==='cancel_requested'?'fa-ban':'fa-hourglass-half'}"></i><div><strong>${request.status==='cancel_requested'?'طلب إلغاء الترقية قيد المراجعة':'طلب تغيير الخطة قيد المراجعة'}</strong><small>${html(request.planCode)} · ${html(request.cycle==='annual'?'سنوي':'شهري')} · ${Number(request.total||0).toLocaleString('en-US')} ر.ي · ${html(request.paymentLabel)}${request.paymentAccount?' · '+html(request.paymentAccount):''}</small>${request.notes?`<small class="mf-upgrade-pending__note">${html(request.notes)}</small>`:''}${request.status==='pending'?`<button type="button" class="mf-upgrade-cancel" data-upgrade-cancel="${html(request.id)}"><i class="fa-solid fa-ban"></i> طلب إلغاء</button>`:'<small class="mf-upgrade-cancel-note">تم رفع طلب الإلغاء، وتبقى الخيارات مقفلة حتى المراجعة.</small>'}</div></div>`:''}<div class="mf-plan-grid">${cards}</div>`;
  el('ozPlanRenew').hidden=true;el('ozPlanRenew').disabled=true;}
 const upgradeMethods=()=>Array.isArray(window.MyfntDefaults?.upgradePaymentMethods)?window.MyfntDefaults.upgradePaymentMethods:[];
 function upgradeMethod(id){return upgradeMethods().find(x=>x.id===id)||null;}
 function renderUpgradeAccounts(){for(const method of upgradeMethods()){const node=document.querySelector(`[data-pay-account-short="${method.id}"]`);if(node)node.textContent=method.account||'غير محدد';}updateUpgradeAccount();}
 function updateUpgradeAccount(){const id=el('ozUpgradePayment')?.value||'',method=upgradeMethod(id),number=el('ozUpgradeAccountNumber'),label=el('ozUpgradeAccountLabel'),copy=el('ozUpgradeCopyAccount');if(label)label.textContent=method?.accountLabel||'رقم الحساب';if(number)number.textContent=method?.account|| (id?'رقم الحساب غير محدد':'اختر طريقة الدفع');if(copy){copy.disabled=!method?.account;copy.dataset.copyValue=method?.account||'';}}
 function openUpgrade(planCode){const registry=window.MyfntPlans,p=registry?.get?.(planCode),activity=activityContext(),d=read();if(!p||!owner())return;if((d.upgradeRequests||[]).some(r=>['pending','cancel_requested'].includes(r.status)))return showToast('يوجد طلب ترقية أو إلغاء قيد المراجعة','warning');el('ozUpgradePlanCode').value=p.code;el('ozUpgradeTitle').textContent=`الترقية إلى ${p.name_ar} — ${p.code}`;el('ozUpgradeDescription').textContent=planDescription(p,activity);el('ozUpgradeMonthlyPrice').textContent=Number(p.monthly_price||0).toLocaleString('en-US')+' ر.ي';el('ozUpgradeAnnualPrice').textContent=Number(p.annual_price||0).toLocaleString('en-US')+' ر.ي';const cycle=el('ozUpgradeCycle');if(cycle)cycle.value='annual';document.querySelectorAll('[data-upgrade-cycle]').forEach(btn=>window.MyfntChoice?.set?.(btn,btn.dataset.upgradeCycle==='annual'));const payment=el('ozUpgradePayment');if(payment)payment.value='';document.querySelectorAll('[data-upgrade-payment]').forEach(btn=>window.MyfntChoice?.set?.(btn,false));if(el('ozUpgradeNotes'))el('ozUpgradeNotes').value='';if(el('ozUpgradeProof'))el('ozUpgradeProof').value='';if(el('ozUpgradeProofName'))el('ozUpgradeProofName').textContent='لم يتم اختيار صورة';renderUpgradeAccounts();updateUpgradeTotal();openWindow('ozUpgradeWindow');}
 function updateUpgradeTotal(){const p=window.MyfntPlans?.get?.(el('ozUpgradePlanCode')?.value),annual=(el('ozUpgradeCycle')?.value||'annual')==='annual',total=Number(annual?p?.annual_price:p?.monthly_price||0);el('ozUpgradeTotal').textContent=total.toLocaleString('en-US')+' ر.ي';if(el('ozUpgradeCycleLabel'))el('ozUpgradeCycleLabel').textContent=annual?'سنوي':'شهري';}
 function renderSupport(){const tickets=read().tickets||[];el('ozSupportDrafts').innerHTML=tickets.length?tickets.slice().reverse().map(t=>`<div class="oz-prod-row"><div><strong>${html(t.subject)}</strong><small>${html(t.body)}</small><small>${html(t.date)} · مسودة لم تُرسل</small></div></div>`).join(''):'<p class="oz-prod-muted">لا توجد مسودات حاليًا.</p>';}
 const renderProfile=()=>{const x=current();if(!x)return;const p=el('ozProfilePhotoPreview');p.textContent='';if(x.user?.avatar){const img=new Image();img.src=x.user.avatar;img.alt='الصورة الشخصية';p.append(img);}else p.textContent=String(x.user?.name||'؟').slice(0,1);const bookings=(window.MyfntRepositories?.bookings?.all?.()||[]),payments=(window.MyfntRepositories?.payments?.all?.()||[]),customers=(window.MyfntRepositories?.customers?.all?.()||[]),plan=String(x.company?.plan||window.MyfntPlans?.defaultCode?.()||'ULTRA').toUpperCase();
  if(el('mfProfileHeroName'))el('mfProfileHeroName').textContent=x.user?.name||'ملفي الشخصي';if(el('mfProfilePlan'))el('mfProfilePlan').textContent=plan;
  el('ozProfileOverview').innerHTML=`<div class="oz-profile-summary"><div class="oz-profile-chip"><i class="fa-solid fa-building"></i><div><strong>${html(x.company?.name||'نشاطي')}</strong><small>الحساب الحالي · ${html(plan)}</small></div></div><div class="oz-profile-stats"><span><i class="fa-solid fa-calendar-check"></i><b>${bookings.length}</b><small>حجز</small></span><span><i class="fa-solid fa-users"></i><b>${customers.length}</b><small>عميل</small></span><span><i class="fa-solid fa-file-invoice-dollar"></i><b>${payments.length}</b><small>سند</small></span></div></div>`;};
 const OWNER_ONLY_WINDOWS=new Set(['ozTeamWindow','ozPlanWindow','myfntMessagesWindow','ozUpgradeWindow','ozSettingsHubWindow','advancedPrefsWindow','bookingUiSettingsWindow','seasonPricingWindow','specialDaysWindow','communicationPolicyWindow','backupCenterWindow','ozSecureExportWindow','companySettingsWindow','usageWindow','syncWindow','cacheWindow','driveWindow','icloudWindow']);
 const ownerOnly=id=>{if(!OWNER_ONLY_WINDOWS.has(id))return false;if(owner())return false;showToast('هذه الصفحة متاحة لمالك الشركة فقط','warning');return true;};
 const applyOwnerVisibility=()=>{const own=owner();document.querySelectorAll('[data-owner-only]').forEach(node=>{node.hidden=!own;node.setAttribute('aria-hidden',String(!own));});const ids=['ozOpenSettingsHub','openBackupCenter','ozOpenSecureExport','diagnosticsBtn'];for(const id of ids){const n=el(id);if(n){n.hidden=!own;n.setAttribute('aria-hidden',String(!own));}}document.querySelectorAll('[data-oz-prod-open="ozTeamWindow"],[data-oz-prod-open="ozPlanWindow"],[data-oz-prod-open="myfntMessagesWindow"],[data-open-admin="companySettingsWindow"],[data-open-admin="advancedPrefsWindow"],[data-open-admin="usageWindow"],[data-open-admin="syncWindow"],[data-open-admin="cacheWindow"],[data-open-admin="driveWindow"],[data-open-admin="icloudWindow"]').forEach(n=>{n.hidden=!own;n.setAttribute('aria-hidden',String(!own));});};
 const open=id=>{if(!logged())return;if(ownerOnly(id))return;const need={ozSupportWindow:'support.write'}[id];if(need&&denied(need))return;if(id==='ozTeamWindow')renderTeam();if(id==='ozPlanWindow')renderPlan();if(id==='ozSupportWindow')renderSupport();if(id==='myfntMessagesWindow')window.MyfntMessages?.render?.();openWindow(id);if(id==='ozPlanWindow')requestAnimationFrame(()=>el('ozPlanWindow')?.scrollTo?.({top:0,left:0,behavior:'auto'}));};
 document.querySelectorAll('[data-oz-prod-open]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.ozProdOpen)));
 el('ozDeviceSessionForm')?.addEventListener('submit',e=>{e.preventDefault();const name=String(el('ozDeviceSessionName')?.value||'').trim();if(!renameCurrentSession(name))return showToast('اكتب اسمًا واضحًا للجهاز من حرفين إلى 50 حرفًا','warning');renderTeam();showToast('تم حفظ اسم هذه الجلسة');});
 el('ozRefreshSessions')?.addEventListener('click',()=>{renderTeam();showToast('تم تحديث سجل الجلسات المحلية');});
 el('ozSupportForm')?.addEventListener('submit',e=>{e.preventDefault();if(denied('support.write'))return;const d=read(),f=new FormData(e.currentTarget),subject=String(f.get('subject')||'').trim(),body=String(f.get('body')||'').trim();if(subject.length<4||body.length<10)return showToast('اكتب موضوعًا وتفاصيل كافية','warning');d.tickets=[...(d.tickets||[]),{id:crypto.randomUUID(),subject,body,date:new Date().toISOString()}];try{save(d);e.currentTarget.reset();renderSupport();showToast('حُفظت مسودة الدعم محليًا؛ لم تُرسل للخادم');}catch{showToast('تعذر حفظ المسودة','warning');}});
 el('ozPlanContent')?.addEventListener('click',async e=>{const more=e.target.closest('[data-plan-more]');if(more){const code=more.dataset.planMore,box=el('ozPlanContent')?.querySelector(`[data-plan-details="${CSS.escape(code)}"]`),expanded=more.getAttribute('aria-expanded')==='true';more.setAttribute('aria-expanded',String(!expanded));more.querySelector('span').textContent=expanded?'عرض المزيد':'عرض أقل';more.querySelector('i')?.classList.toggle('fa-chevron-down',expanded);more.querySelector('i')?.classList.toggle('fa-chevron-up',!expanded);if(box)box.hidden=expanded;return;}const b=e.target.closest('[data-plan-upgrade]');if(b){openUpgrade(b.dataset.planUpgrade);return;}const cancel=e.target.closest('[data-upgrade-cancel]');if(cancel){if(!owner())return;const d=read(),req=(d.upgradeRequests||[]).find(r=>r.id===cancel.dataset.upgradeCancel&&r.status==='pending');if(!req)return;const ok=await ozConfirm('سيتم إرسال طلب إلغاء للترقية الحالية، وستظل خيارات الخطط مقفلة حتى تتم مراجعة الإلغاء. هل تريد المتابعة؟',{title:'طلب إلغاء الترقية',confirmLabel:'رفع طلب الإلغاء'});if(!ok)return;req.status='cancel_requested';req.cancelRequestedAt=new Date().toISOString();save(d);renderPlan();showToast('تم رفع طلب إلغاء الترقية','warning');}});
 el('ozUpgradeForm')?.addEventListener('click',e=>{const cycle=e.target.closest('[data-upgrade-cycle]');if(cycle){e.preventDefault();const root=cycle.parentElement;window.MyfntChoice?.single?.(root,cycle,'[data-upgrade-cycle]');if(el('ozUpgradeCycle'))el('ozUpgradeCycle').value=cycle.dataset.upgradeCycle;updateUpgradeTotal();return;}const pay=e.target.closest('[data-upgrade-payment]');if(pay){e.preventDefault();window.MyfntChoice?.single?.(pay.parentElement,pay,'[data-upgrade-payment]');if(el('ozUpgradePayment'))el('ozUpgradePayment').value=pay.dataset.upgradePayment;updateUpgradeAccount();}});
 el('ozUpgradeCopyAccount')?.addEventListener('click',async e=>{const value=e.currentTarget.dataset.copyValue||'';if(!value)return showToast('رقم الحساب غير محدد','warning');try{await navigator.clipboard.writeText(value);showToast('تم نسخ رقم الحساب');}catch{showToast('تعذر نسخ رقم الحساب','warning');}});
 const readFileDataUrl=file=>new Promise((resolve,reject)=>{if(!file)return resolve('');const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(Error('تعذر قراءة صورة الإشعار'));reader.readAsDataURL(file);});
 el('ozUpgradeProof')?.addEventListener('change',e=>{const file=e.target.files?.[0];const label=el('ozUpgradeProofName');if(label)label.textContent=file?file.name:'لم يتم اختيار صورة';});
 el('ozUpgradeForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!owner())return;const d=read(),code=el('ozUpgradePlanCode').value,p=window.MyfntPlans?.get?.(code);if(!p)return;const annual=(el('ozUpgradeCycle')?.value||'annual')==='annual',method=el('ozUpgradePayment')?.value||'',total=Number(annual?p.annual_price:p.monthly_price||0),methodInfo=upgradeMethod(method),labels={floosak:'فلوسك',cash:'كاش',mobile_money:'موبايل موني',kuraimi:'كريمي حاسب',jawali:'جوالي',jeeb:'جيب'},notes=String(el('ozUpgradeNotes')?.value||'').trim(),proofFile=el('ozUpgradeProof')?.files?.[0]||null;if(!method)return showToast('اختر طريقة الدفع','warning');const account=methodInfo?.account||'';const accountText=account?` إلى الحساب ${account}`:' (رقم الحساب غير محدد بعد)';const ok=await ozConfirm(`رفع طلب ترقية إلى ${p.name_ar} بقيمة ${total.toLocaleString('en-US')} ر.ي عبر ${labels[method]}${accountText}؟ بعد الرفع سيُغلق تغيير الخطة حتى مراجعة الطلب.`,{title:'تأكيد طلب الترقية',confirmLabel:'رفع الطلب'});if(!ok)return;let proofDataUrl='';if(proofFile){if(!/^image\//.test(proofFile.type))return showToast('أرفق صورة صحيحة للإشعار','warning');if(proofFile.size>4*1024*1024)return showToast('صورة الإشعار أكبر من 4MB','warning');proofDataUrl=await readFileDataUrl(proofFile);}d.upgradeRequests=[...(d.upgradeRequests||[]),{id:crypto.randomUUID(),status:'pending',planCode:code,cycle:annual?'annual':'monthly',total,paymentMethod:method,paymentLabel:labels[method],paymentAccount:account,notes,proofName:proofFile?.name||'',proofType:proofFile?.type||'',proofDataUrl,createdAt:new Date().toISOString()}];save(d);closeWindow('ozUpgradeWindow',{skipHistory:true});renderPlan();showToast('تم رفع طلب الترقية وإغلاق اختيار الخطط حتى المراجعة');});
 el('ozOpenSettingsHub')?.addEventListener('click',()=>{if(ownerOnly('ozSettingsHubWindow'))return;openWindow('ozSettingsHubWindow');});
 el('ozSettingsHubWindow')?.addEventListener('click',e=>{const b=e.target.closest('[data-oz-settings-target]');if(!b)return;const id=b.dataset.ozSettingsTarget;if(ownerOnly(id))return;closeWindow('ozSettingsHubWindow',{skipHistory:true});if(id==='advancedPrefsWindow'){window.OzanAdvanced?.openPreferences?.();return;}if(id==='communicationPolicyWindow'){openWindow(id);document.dispatchEvent(new Event('myfnt:open-communication-settings'));return;}if(typeof prepareAdminWindow==='function')prepareAdminWindow(id);openWindow(id);});
 for(const id of ['advancedPrefsWindow','bookingUiSettingsWindow','seasonPricingWindow','specialDaysWindow','communicationPolicyWindow']){const win=el(id),head=win?.querySelector('.window__header');if(!head)continue;const back=document.createElement('button');back.className='oz-settings-back';back.type='button';back.innerHTML='<i class="fa-solid fa-arrow-right"></i> جميع الإعدادات';head.append(back);back.addEventListener('click',()=>{closeWindow(id,{skipHistory:true});openWindow('ozSettingsHubWindow');});}
 el('ozLoginBtn')?.addEventListener('click',()=>requestAnimationFrame(renderProfile));
 document.addEventListener('myfnt:media-ready',()=>requestAnimationFrame(renderProfile));
 document.querySelectorAll('[data-oz-profile-link]').forEach(btn=>btn.addEventListener('click',()=>{window.OzanProfilePage?.close?.();open(btn.dataset.ozProfileLink);}));
 el('ozProfilePhotoFile')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>3*1024*1024||!/^image\/(png|jpeg|webp)$/.test(file.type))return showToast('اختر PNG أو JPG أو WebP أصغر من 3MB','warning');try{const bm=await createImageBitmap(file),c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,256,256);const side=Math.min(bm.width,bm.height);ctx.drawImage(bm,(bm.width-side)/2,(bm.height-side)/2,side,side,0,0,256,256);bm.close?.();const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('تعذر ضغط الصورة')),'image/jpeg',.74)),x=current();if(!x)return;const url=await window.MyfntMedia?.put?.('avatar:'+x.s.userId,blob);if(!url)throw Error('تعذر حفظ الصورة');window.MyfntMedia?.defineAvatar?.(x.user,url);try{localStorage.setItem('ozan.auth.demo.v1',JSON.stringify(auth().data));}catch{}renderProfile();showToast('تم حفظ الصورة الشخصية في IndexedDB');}catch{showToast('تعذر معالجة الصورة','warning');}finally{e.target.value='';}});
 el('ozProfilePasswordForm')?.addEventListener('submit',async e=>{e.preventDefault();const old=el('ozCurrentPass').value,next=el('ozNextPass').value,again=el('ozRepeatPass').value;if(next.length<12||next!==again)return showToast('تحقق من تطابق كلمتي المرور؛ الحد الأدنى 12 حرفًا','warning');const btn=e.currentTarget.querySelector('button[type=submit]');btn.disabled=true;try{await auth().changeLocalPassword(old,next);e.currentTarget.reset();showToast('تم تغيير كلمة مرور الحساب المحلي');}catch(err){showToast(err.message||'تعذر تغيير كلمة المرور','warning');}finally{btn.disabled=false;}});
 // Single-account mode: compatibility gates now require an authenticated principal session only.
 const originalGate=window.OzanGate?.blockedWindow;
 if(originalGate)window.OzanGate.blockedWindow=function(id){if(originalGate(id))return true;if(OWNER_ONLY_WINDOWS.has(id)&&!owner()){showToast('هذه الصفحة متاحة لمالك الشركة فقط','warning');return true;}const needed={bookingFormWindow:'bookings.write',receiptWindow:'payments.write',packagesWindow:'packages.write',bookingsAdminWindow:'bookings.read'}[id];return needed?denied(needed):false;};
 applyOwnerVisibility();document.addEventListener('ozan:auth-changed',applyOwnerVisibility);document.addEventListener('ozan:scope-changed',applyOwnerVisibility);window.OzanProductionTools={renderProfile,renderTeam,renderPlan,renderSupport,open,read,permissions,applyOwnerVisibility,sessions:readSessions,ensureCurrentSession};
})();
