/* OZAN 2.2.3 optional encrypted, compact, ID-preserving backup. Never export auth tokens/passwords. */
'use strict';
(()=>{
 const el=id=>document.getElementById(id),enc=new TextEncoder(),dec=new TextDecoder(),ab2b64=buf=>{const x=new Uint8Array(buf);let s='';for(let i=0;i<x.length;i+=32768)s+=String.fromCharCode(...x.subarray(i,i+32768));return btoa(s);},b642ab=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 const assert=()=>{const own=window.OzanScope?.owner();if(!own)throw Error('سجل الدخول أولًا');if(!crypto.subtle)throw Error('التشفير غير مدعوم في هذا المتصفح');return own;};
 const compact=rows=>{const fields=[...new Set(rows.flatMap(r=>Object.keys(r||{})))].sort();return {fields,rows:rows.map(r=>fields.map(k=>r[k]??null))};};
 const expand=part=>{if(!part||!Array.isArray(part.fields)||!Array.isArray(part.rows)||part.rows.length>500000)throw Error('تنسيق السجلات غير صالح');if(new Set(part.fields).size!==part.fields.length||part.fields.some(x=>typeof x!=='string'||x.length>80))throw Error('أسماء الحقول غير صالحة');return part.rows.map(row=>{if(!Array.isArray(row)||row.length!==part.fields.length)throw Error('صفّ غير صالح');return Object.fromEntries(part.fields.map((k,i)=>[k,row[i]]));});};
 const hex=buf=>[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');
 async function key(pass,salt){const k=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},k,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
 async function snapshot(){const own=assert(),full=window.MyfntDomainRuntime?.lazy&&window.MyfntQuery?.exportLegacyDataset?await window.MyfntQuery.exportLegacyDataset():null;const p={schema:'ozan-backup-v1',owner:own,appVersion:APP_VERSION,createdAt:new Date().toISOString(),bookings:full?.bookings||(window.MyfntRepositories?.bookings?.snapshot?.()||[]),customers:full?.customers||(window.MyfntRepositories?.customers?.snapshot?.()||[]),packages:(window.MyfntRepositories?.packages?.snapshot?.()||[]),receipts:full?.receipts||(window.MyfntRepositories?.payments?.snapshot?.()||[]),specialDays:(window.MyfntRepositories?.specialDays?.snapshot?.()||[]),settings:(window.MyfntRepositories?.settings?.snapshot?.()||{}),notificationRead:[...state.notificationRead],notificationReadAt:state.notificationReadAt,syncAudit:state.syncAudit,financeAudit:window.MyfntFinance?.audit?.()||[],financeCustomerNotes:window.MyfntFinance?.notes?.()||{},bookingHistory:typeof ozHistory!=='undefined'?ozHistory:{},experience:typeof ozPreferences!=='undefined'?ozPreferences:{},...(window.OzanAdvanced?.settingsBackup?.()||{})};
  return {kind:'ozan-compact-v1',owner:own,createdAt:p.createdAt,bookings:compact(p.bookings),receipts:compact(p.receipts),rest:{...p,bookings:undefined,receipts:undefined}};}
 async function encrypt(pass){const item=await snapshot(),raw=enc.encode(JSON.stringify(item)),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),secret=await key(pass,salt);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},secret,raw);return {type:'ozan-encrypted-compact',version:1,algorithm:'PBKDF2-SHA256+AES-256-GCM',iterations:250000,createdAt:item.createdAt,salt:ab2b64(salt),iv:ab2b64(iv),payload:ab2b64(encrypted)};}
 async function decrypt(file,pass){if(file.size>30*1024*1024)throw Error('حجم الملف كبير جدًا');const wrapper=JSON.parse(await file.text());if(wrapper.type!=='ozan-encrypted-compact'||wrapper.version!==1||wrapper.iterations!==250000||typeof wrapper.payload!=='string')throw Error('ملف غير مطابق للإصدار المدعوم');const salt=b642ab(wrapper.salt),iv=b642ab(wrapper.iv);if(salt.length!==16||iv.length!==12)throw Error('بيانات التشفير غير سليمة');let raw;try{raw=await crypto.subtle.decrypt({name:'AES-GCM',iv},await key(pass,salt),b642ab(wrapper.payload));}catch{throw Error('كلمة المرور غير صحيحة أو الملف تالف');}const compactData=JSON.parse(dec.decode(raw)),owner=assert();if(compactData.kind!=='ozan-compact-v1'||compactData.owner?.companyId!==owner.companyId||compactData.owner?.userId!==owner.userId)throw Error('النسخة تخص حسابًا أو شركة مختلفة');if(!window.MyfntAccess?.isActive?.())throw Error('يجب تفعيل الاشتراك قبل استيراد نسخة البيانات');const bookings=expand(compactData.bookings),receipts=expand(compactData.receipts),bookIds=new Set(bookings.map(b=>b.id));if(bookIds.size!==bookings.length||receipts.some(r=>!bookIds.has(r.bookingId)))throw Error('المعرّفات أو روابط السندات غير متطابقة');const p={...compactData.rest,bookings,receipts};if(p.schema!=='ozan-backup-v1')throw Error('نسخة غير مدعومة');return {type:'ozan-backup',hashAlgorithm:'SHA-256',sha256:hex(await crypto.subtle.digest('SHA-256',enc.encode(JSON.stringify(p)))),payload:p};}
 function download(data,name){const blob=new Blob([JSON.stringify(data)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
 el('ozOpenSecureExport')?.addEventListener('click',()=>{if(window.OzanPermissions?.denied('exports.read'))return;openWindow('ozSecureExportWindow');});
 el('ozSecureExportForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!window.MyfntFeatureGate?.require?.('encrypted_export'))return;const quota=window.MyfntFeatureGate?.check?.('encrypted_exports_monthly_limit',{message:'تم بلوغ حد التصدير المشفر الشهري لخطتك'}),general=window.MyfntFeatureGate?.check?.('exports_monthly_limit',{message:'تم بلوغ حد التصدير الشهري لخطتك'});if(quota?.ok&&Number.isFinite(quota.limit)&&quota.remaining<=0)return window.showToast?.('تم بلوغ حد التصدير المشفر الشهري لخطتك','warning');if(quota&&!quota.ok)return window.showToast?.(quota.message,'warning');if(general&&!general.ok)return window.showToast?.(general.message,'warning');const f=e.currentTarget,d=new FormData(f),pass=String(d.get('pass')),confirm=String(d.get('confirm'));if(pass.length<12||pass!==confirm)return showToast('تأكد من تطابق كلمتي المرور والحد الأدنى 12 حرفًا','warning');const btn=f.querySelector('[type="submit"]');btn.disabled=true;btn.setAttribute('aria-busy','true');try{const x=await encrypt(pass);download(x,'myevent-encrypted-'+new Date().toISOString().slice(0,10)+'.json');window.MyfntFeatureGate?.consume?.('encrypted_exports_monthly_limit',1);window.MyfntFeatureGate?.consume?.('exports_monthly_limit',1);f.reset();showToast('نُزّلت نسخة مشفّرة ومختصرة. احفظ كلمة المرور بأمان.');}catch(err){showToast(err.message||'تعذّر التصدير','warning');}finally{btn.disabled=false;btn.removeAttribute('aria-busy');}});
 el('ozSecureInspectForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),file=d.get('file'),pass=String(d.get('pass')||'');if(!file||!file.size)return;const btn=f.querySelector('button[type=submit]');btn.disabled=true;btn.setAttribute('aria-busy','true');try{const x=await decrypt(file,pass);download(x,'myevent-verified-decrypted-'+new Date().toISOString().slice(0,10)+'.json');f.reset();showToast('تم فحص السلامة والملكية وتنزيل النسخة المفككة. لم تُستبدل أي بيانات.');}catch(err){showToast(err.message||'فشل فحص النسخة','warning');}finally{btn.disabled=false;btn.removeAttribute('aria-busy');}});
 window.OzanSecureExport={compact,expand,encrypt,decrypt};
})();
